const help = (prefix) => {
    return `Normas del Grupo


    ⛩Normas/Reglas del Grupo⛩
    Bienvenidos a la Actualización de 2021 con nuevos movimientos y mejorando la calidad para todos ustedes, "#SomosAnimeYosai" por amantes del animes Otakus y muchos mas...!
    
    ✅ RESPETAR A LOS MIEMBROS DEL GRUPO
    ❌ NO HAGAS COMENTARIOS INAPROPIADOS Y EVITA LOS EMOJIS
    ❌ NO ACOSAR, NI INSULTAR A LOS MIEMBROS
    ✅ PERMITIR TODO TIPO DE ECCHI (TODO,SIN EXCEPCIONES) Y SOLO LOS ESTRENO DE H3NTAI EN EMISION CORTA
    ❌ NO SE PERMITE EL CONTENIDO PORNOGRAFICO REAL, CP, HENTAI, U OTROS
    ❌NO SE PERMITEN LAS PELICULAS DE IMAGEN REAL
    ❌ "NUEVO ANUNCIO" YA NO APORTAR EL FORMATO DE ANIME EN 240p (OJO SOLO SE PUEDE ENVIAR EN 360p - 480p - 720p y FULL HD)
    ✅ COMPARTE TU CONTENIDO COMO IMAGENES, MEMES, MUSICA, VIDEOS Y MUCHO MAS DE LA CULTURA JAPONESA/ANIME
    ✅ COMPARTIMOS MUSICA, OST ORIGINALES POR FORMATO FLAC / WAV ( OJO LOS ORIGINALES PESAN MAS DE 30mb DE MEMORIA)
    ❌ NO HACER FLOOD CON GIF, STICKER O IMAGENES 
    ❌ NO SPAM/LINKS DE CUALQUIER TIPO INCLUYENDO GRUPOS O CANALES DE TELEGRAM Y WHATSAPP; SOLO SERAN ACEPTADOS LINKS DE YOUTUBE Y TWITTER CON CONTENIDO OFICIAL DE ANIME
    ❌ SI EL PROBLEMA SIGUE DESPUES DE PUBLICAR SPAM EL BOT LO ELIMINARA EN BREVE Y TU SERAS SANCIONADO
    ✅ PARA VER LA LISTA DE PALABRA PROHIBIDA, ESCRIBE AQUI EN GRUPO 👉🏻 /io
    
    🔰SORTEO Y EVENTO PARA TODOS USTEDES ABRIRE EN SU PROXIMO TEMPORADA VERANO 2021 CON GRANDES REGALO Q DESEA DARTE ...`
}

exports.help = help